account/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name='account'

urlpatterns = [
  path('', views.index, name='userprofile'),
  path('validate-username', csrf_exempt(views.UsernamevalidationView.as_view()), name='validate-username'),
  path('validate-email', csrf_exempt(views.EmailValidation.as_view()), name='validate-email'),
  path('activate/<uid64>/<token>/', views.VerificationView.as_view(), name='activate'),
  path('update/', views.profile_update, name='update'),
  path('change_password/', views.update_password, name='change_password'),
  path('whishlist/', views.whishlist,name='whishlist'),
  path('add_to_wishlist/<int:id>/', views.add_to_whishlist, name='add_to_wishlist'),
]

agropoultry/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from home.views import aboutUs, contactUs, SearchResultsView,searchresults
from product.views import process_payment, payment_done, payment_cancelled
from account.views import RegistrationView,LoginView,logoutPage
from django.contrib.auth import views as auth_views
# from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('products/', include('product.urls', namespace='products')),
    path('services/', include('service.urls', namespace='services')),
    path('register/', RegistrationView.as_view(), name='register'),
    path('account/', include('account.urls', namespace='account')),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search/', searchresults, name='search_results'),
    # path('validate-username', csrf_exempt(UsernamevalidationView.as_view()), name='validate-username'),
    # path('validate-email', csrf_exempt(EmailValidation.as_view()), name='validate-email'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logoutPage,name='logout'),
    path('about/', aboutUs, name='about'),
    path('contact/', contactUs, name='contact'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('process_payment/', process_payment, name='process_payment'),
    path('payment_done/', payment_done, name='payment_done'),
    path('payment_cancelled/', payment_cancelled, name='payment_cancelled'),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # authentication views from django
    path('reset_password/', 
    auth_views.PasswordResetView.as_view(template_name='account/password_reset.html'), 
    name='password_reset'),
    path('reset_password/done/', 
    auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_sent.html'), 
    name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form.html'), 
    name='password_reset_confirm'),
    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
    name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .import views


app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    
]

product/urls.py
from django.urls import path
from .import views

app_name='products'

urlpatterns = [
    path('', views.index, name='products'),
    path('cart/', views.add_to_cart, name='cart_details'),
    path('get_cart_data/', views.get_cart_data, name='get_cart_data'),
    path("change_quan",views.change_quan,name="change_quan"),
    path('checkout/', views.checkout, name='checkout'),
    path('<int:id>/<str:slug>/',views.product_details, name='product_details'),
    path('category/<str:category_slug>/', views.show_category, name='show_category'),
    path('<str:cslug>/', views.category_products, name='category_products'), 

    ] 

product/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey


# Create your models here.
class Category(MPTTModel):
    STATUS = (
        ('True','True'),
        ('False','False'),
    )
    # id = models.AutoField(unique=True)
    title = models.CharField(max_length=100)
    parent = TreeForeignKey('self', blank=True,null=True, on_delete=models.CASCADE, related_name='children')
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    slug = models.SlugField(null=False,unique=True)
    image = models.ImageField(blank=True, upload_to='categories/%Y/%m/%d/')
    status = models.CharField(max_length=5, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" height="50" width="50">' %self.image.url)
        return "No image found"
            
    def get_absolute_url(self):
        return reverse('products:category_products', args=[self.slug])   


    class Meta:
        verbose_name_plural = 'categories'

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title

class Product(models.Model):
    STATUS = (
        ('True','True'),
        ('False','False'),
    )
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    keywords = models.CharField(max_length=255)
    description = RichTextUploadingField()#models.CharField(max_length=255)
    slug = models.SlugField(null=False, unique=True)
    image = models.ImageField(blank=True, upload_to='products/')
    status = models.CharField(max_length=5, choices=STATUS)
    available = models.BooleanField(default=True)
    details = RichTextUploadingField()#models.TextField()
    specification = RichTextUploadingField()#models.CharField(max_length=255)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    amount = models.IntegerField()
    miniamount = models.IntegerField()
    in_stock = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(User, related_name='users_wishlist',blank=True)

    

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" height="50" width="50">' %self.image.url)
        return "No image found"

    def get_absolute_url(self):
        return reverse('products:product_details',args=[self.id,self.slug])   

    def __str__(self):
        return self.title

class Picture(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True)
    image = models.ImageField(blank=True, upload_to='pictures/')
    # status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Customer(models.Model):
    GENDER = (
        ('male','male'),
        ('female','female'),
    )
    TITLE = (
        ('mr.','mr.'),
        ('mrs.','mrs.'),
        ('ms.','ms.'),
        ('dr.','dr.'),
        ('prof.', 'prof.'),
        ('king','king'),
        ('chief','chief'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True,blank=True)
    gender = models.CharField(max_length=6, choices=GENDER, default='male')
    title = models.CharField(max_length=5, choices=TITLE)
    
    # device = models.CharField(max_length=200,null=True, blank=True)
    

    def __str__(self):
        name = self.user.username
        return str(name)
        

class Cart(models.Model):
    customer =models.ForeignKey(User,on_delete = models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    quantity = models.IntegerField()
    status = models.BooleanField(default=False)
    created_at =models.DateTimeField(auto_now_add=True,null=True)
    update_at = models.DateTimeField(auto_now=True,null=True)

    @property
    def get_total(self):
        total = self.quantity * self.product.price
        return total

    def __str__(self):
        return "Cart Id:{} attached to customer:{}".format(str(self.id),str(self.customer))

class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    cart_id = models.CharField(max_length=250)
    product_ids = models.CharField(max_length=250)
    complete = models.BooleanField(default=False,null=True,blank=True)
    invoice_id = models.CharField(max_length=100,null=True)# invoice id

    # @property
    # def get_cart_total(self):
    #     orderitems = self.orderitem_set.all()
    #     total = sum([item.get_total for item in orderitems])
    #     return total

    # @property
    # def get_cart_items(self):
    #     orderitems = self.orderitem_set.all()
    #     total = sum([item.quantity for item in orderitems])
    #     return total

    def __str__(self) :
        return  "Order of ID:{} on this date: {}".format(str(self.id),str(self.date_ordered.strftime('%d /%m/%Y')))



class ShippingAddress(models.Model):
    customer = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    address = models.CharField(max_length=150,null=False)
    city = models.CharField(max_length=150,null=False)
    state = models.CharField(max_length=150,null=False)
    zipcode = models.CharField(max_length=150,null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

class Notification(models.Model):
    recipient = models.ForeignKey(Customer, on_delete=models.CASCADE)
    text = RichTextField()
    read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Notification for: self.recipient.user"

product/forms.py
from django import forms
from django import forms
from django.forms import widgets
from .models import ShippingAddress


class ShippingForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['address','city','state','zipcode']
        labels = {
            'address':'',
            'city':'',
            'state':'',
            'zipcode':''
        }
        
        widgets = {
            'address':forms.TextInput(attrs={'placeholder':'Enter Address','address':'address'}),
            'city':forms.TextInput(attrs={'placeholder':'Enter City','city':'city'}),
            'state':forms.TextInput(attrs={'placeholder':'Enter State','state':'state'}),
            'zipcode':forms.TextInput(attrs={'placeholder':'Enter Zipcode','zipcode':'zipcode'}),
        }

templates/products/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
cart
{% endblock title %}
{% block description %}
Mega Poultry Farm
{% endblock description %}
{% block keywords %}
Agro,Poultry,Hatchery,Chicken, Machinery
{% endblock keywords %}
{% block header %}
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  
{% endblock header %}
{% block aside %}
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url({% static 'images/img_bg_6.jpg' %});">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Shopping Cart</h1>
							<h2>Inuwa Agro </h2>
						</div>
					</div>
				</div>
			</div>
		</div>
</header>
{% endblock aside %}

{% block products %}

<div id="fh5co-contact">
	<div class="container">
	<section id="cart_items">
		<div class="container">
			
			
			<div class="table-responsive cart_info">
               
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Product</td>
							<td class="description">Description</td>
							<td class="price">UnitPrice</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td><i class="fa fa-trash"></i></td>
						</tr>
					</thead>
					<tbody>
					{% if items|length == 0 %}
					<tr>
					<td colspan="6" style="">
    				<div class="container-fluid">
        				<div class="jumbotron alert alert-danger" style="text-align:center;">
           			 	&times; Your Shopping Cart is empty !!!  
        				</div>
    				</div>
					</td>
					</tr>
					{% else %} 
                      {% for item in items %} 
					 
						<tr class="pcart">
							<td class="cart_product">
								<a href="{{ item.product.get_absolute_url }}"><img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static 'images/no-image.png' %}{% endif %}" style="width:50px;height:50px;"alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a></h4>
								<p>{{ item.product.description|safe | truncatechars_html:50 }}</p>
							</td>
							<td class="cart_price">
								<p>&#8358;{{ item.product.price }}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
								<img class="cart_quantity_up" onclick="change_quan('{{item.id}}','plus')" src="{% static 'images/plus.jpg' %}" style="width:30px;height:30px;">	
								<input class="cart_quantity_input " type="text" name="quantity" value="{{ item.quantity }}" autocomplete="off" size="2" id="cart{{ item.id }}">
								<img class="cart_quantity_up" onclick="change_quan('{{item.id}}','minus')" src="{% static 'images/minus.jpg' %}" style="width:30px;height:30px;">
							</td>
							<td class="cart_total">
								<p class="cart_total_price">&#8358;{{ item.get_total }}</p>
							</td>
							<td class="cart_delete">
								<button class="cart_quantity_delete" onclick="remove_cart('{{item.id}}')" ><i class="fa fa-times"></i></button>
							</td>
						</tr>
                    {% endfor %}  

                   	{% endif %}  
					</tbody>
				</table>
			</div>
			
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<input type="checkbox">
								<label>Use Coupon Code</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Use Gift Voucher</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Estimate Shipping & Taxes</label>
							</li>
						</ul>
						<ul class="user_info">
							<li class="single_field">
								<label>Country:</label>
								<select>
									<option>Nigeria</option>
									<option>Ghana</option>
									<option>Cameroun</option>
									<option>Liberia</option>
									<option>Siereleon</option>
									<option>Benin</option>
									<option>Ivory Coast</option>
									<option>Togo</option>
								</select>
								
							</li>
							{% comment %} <li class="single_field">
								<label>Region / State:</label>
								<select>
									<option>Select</option>
									<option>Dhaka</option>
									<option>London</option>
									<option>Dillih</option>
									<option>Lahore</option>
									<option>Alaska</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
							
							</li> {% endcomment %}
							<li class="single_field zip-field">
								<label>Zip Code:</label>
								<input type="text">
							</li>
						</ul>
						<a class="btn btn-default update" href="">Get Quotes</a>
						<a class="btn btn-default check_out" href="{% url 'products:products' %}">Continue Shopping</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
						    <li>Quantity: <span id="quantity"></span></li>
							{% comment %} <li id="item_total">Cart Sub Total <span>${{ order.get_cart_total }}</span></li> {% endcomment %}
							<li>Eco Tax <span>&#8358;2</span></li>
							<li>Shipping Cost <span>Free</span></li>
							<li >Cart Grand Total <span id="grand_total">&#8358;</span></li>
						</ul>
							<a class="btn btn-default update" href="{% url 'products:cart_details' %}">Update</a>
							<a class="btn btn-default check_out" href="{% url 'products:checkout' %}">Checkout</a>
					</div>
				</div>
			</div>
		</div>
	</section><!--/#do_action-->
	
	</div>
</div>

{% endblock  %}
	
{% block counter %}
<script src="{% static 'js/jquery.js' %}"></script>
{% comment %} <script src="{% static 'js/cart.js' %}"></script> {% endcomment %}
<script>
       function grandTotal(){
           $.ajax({
               url:"{% url 'products:get_cart_data' %}",
               type:'get',
               success:function(data){
                   //p = Math.round(100-((data.offer/data.total)*100),2)
                   //save = data.total-data.offer;
				   gtotal = data.total + 2
                   $("#item_total").html("&#x20A6;"+data.total);
                    $("#quantity").html(data.quantity+" Items");
					$("#cartitems").html(data.quantity);
                    $("#grand_total").html("&#8358;"+ gtotal+".00");
                    //$("#btamt").html("&#8377;"+data.offer);

               }
           })
       }
       grandTotal();

       function change_quan(id,action){
           let old = $("#cart"+id).val();
            
           quan = 0
           if(action=="plus"){
               quan += parseInt(old)+1
           }else{
               quan += parseInt(old)-1
           }
           


           $("#cart"+id).val(quan);
           
           $.ajax({
               url:"{% url 'products:change_quan' %}",
               type:"get",
               data:{cid:id, quantity:quan},
               success:function(data){
                   grandTotal();
                 if(data==0){
                    remove_cart(id);
                 }
               }
           })
       }

       function remove_cart(id){
           $.ajax({
               url:"{% url 'products:change_quan' %}",
               data:{delete_cart:id},
               success:function(data){
                    grandTotal();
                    $("#row"+id).hide();
               }

           })
       }
</script>
<div id="fh5co-started">
<div class="container">
<div class="row animate-box">

</div> 
</div>
</div>
</div>

{% endblock counter %}

templates/products/checkout.html
{% extends "base.html" %}
{% load static %}
{% block title %}
 {{ setting.title }} | Checkout
{% endblock title %}
{% block description %}
 {{ setting.description }}
{% endblock description %}
{% block keywords %}
 {{ setting.keywords }}
{% endblock keywords %}
{% block header %}
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  
{% endblock header %}
{% block aside %}
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url({% static 'images/img_bg_6.jpg' %});">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Checking out</h1>
							<h2>Inuwa Agro </h2>
						</div>
					</div>
				</div>
			</div>
		</div>
</header>
{% endblock aside %}
{% block products %}
<div id="fh5co-contact">
	<div class="container">
	<section id="cart_items">
		<div class="container">
			
{% comment %} 
			<div class="step-one">
				<h2 class="heading">Step1</h2>
			</div> {% endcomment %}
			<div class="checkout-options">
				<h3>New User</h3>
				<p>Checkout options</p>
				<ul class="nav">
					<li>
						<label><input type="checkbox"> Register Account</label>
					</li>
					<li>
						<label><input type="checkbox"> Guest Checkout</label>
					</li>
					<li>
						<a href=""><i class="fa fa-times"></i>Cancel</a>
					</li>
				</ul>
			</div><!--/checkout-options-->
			 {% comment %} {% if messages %}
			 {% for msg in messages %}
			  <div class="alert alert-{{msg.level_tag}} text-center">{{ msg }}</div>
			 {% endfor %}

			 {% else %}
			 {% endif %} {% endcomment %}

			<div class="register-req">
				<p>Please use Register And Checkout to easily get access to your order history, or use Checkout as Guest</p>
			</div><!--/register-req-->

			<div class="shopper-informations">
				<div class="row">
					<div class="col-sm-6">
						<div class="shopper-info">
							<p>Shipping Information</p>
							{% include "partials/_messages.html" %}
							<form action="{% url 'products:checkout' %}" method="POST" name="shipping">
							   {% csrf_token %}
							   {% comment %} {{ form.customer }} {% endcomment %}
							   <input type="text" name="customer" id="id_customer" value="{{request.user}}" required="false" disabled="true">
							   {{ form.address }}
							   {{ form.city }}
							   {{ form.state}}
							   {{ form.zipcode }}
							   {% comment %} 
							    <input type="text"  value="{{ request.user.username }}",name="customer">
								<input type="text" placeholder="User Address" name="address">
								<input type="text" placeholder="Enter City" name="city">
								<input type="text" placeholder="Enter State" name="state">
								<input type="text" placeholder="Enter Zipcode" name="zipcode">{% endcomment %}
								<button class="btn btn-primary">Send Info</button>
							</form>
							
							
						</div>
					</div>
					<div class="col-sm-6 clearfix">
					<div class="chose_area">
						<div class="order-message">
							
						    
							  <p class="text-center">Order Summary</p>
							
							<div class="row register-req">
                            
                              
							{% for item in items %}
							<div class="row">
							 <div class="col-sm-3">
							   <img src="{{ item.product.image.url}}" style="width:60px;height:60px;">
							 </div>
							 <div class="col-sm-3">
							  <p>{{ item.product.title }}</p>
							 </div>
							 <div class="col-sm-3">
							 <p>&#8358;{{ item.product.price }}</p>
							 </div>
							 <div class="col-sm-3">
							 <p>{{ item.quantity }}</p>
							 </div>
							</div>
							{% endfor %} 
							</div>
						
							
						</div>
						<div class="row">
						      <a class="btn btn-primary" href="{% url 'products:cart_details' %}">Back To Cart</a>
							  {% if data %}
							   <a class="btn btn-primary" href="{% url 'process_payment' %}">Proceed To Payment</a>
							  {% else %}
							  {% endif %}
							  
							</div>
					</div>
					</div>
					{% comment %} <div class="col-sm-4">
						<div class="order-message">
							<p>Shipping Order</p>
							<textarea name="message"  placeholder="Notes about your order, Special Notes for Delivery" rows="16"></textarea>
							<label><input type="checkbox"> Shipping to bill address</label>
						</div>	
					</div>					 {% endcomment %}
				</div>
			</div>
			
{% comment %} 
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Product</td>
							<td class="description">Description</td>
							<td class="price">UnitPrice</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
					{% for item in items %}
					  	<tr id={{ item.id }}>
							<td class="cart_product">
								<a href=""><img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static 'images/no-image.png' %}{% endif %}" style="width:50px;height:50px;"alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{ item.product.title }}</a></h4>
								<p>{{ item.product.description }}</p>
							</td>
							<td class="cart_price">
								<p>&#8358;{{ item.product.price }}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
								<img class="cart_quantity_up" onclick="change_quan('{{item.id}}','plus')" src="{% static 'images/plus.jpg' %}" style="width:30px;height:30px;">	
								<input class="cart_quantity_input " type="number" name="quantity" value="{{ item.quantity }}" autocomplete="off" size="2" id="cart{{ item.id }}">
								<img class="cart_quantity_up" onclick="change_quan('{{item.id}}','minus')" src="{% static 'images/minus.jpg' %}" style="width:30px;height:30px;">
							</td>
							<td class="cart_total">
								<p class="cart_total_price">&#8358;{{ item.get_total }}</p>
							</td>
							<td class="cart_delete">
								<button class="cart_quantity_delete" onclick="remove_cart('{{item.id}}')" ><i class="fa fa-times"></i></button>
							</td>
						</tr>
                    {% endfor %}
						
						<tr>
							<td colspan="4">&nbsp;</td>
							<td colspan="2">
								<table class="table table-condensed total-result">
								   <tr>
										<td>Cart Sub Total</td>
										<td id="item_total"></td>
									</tr>
									
									<tr>
										<td>Exo Tax</td>
										<td >&#8358;2</td>
									</tr>
									<tr class="shipping-cost">
										<td>Shipping Cost</td>
										<td>Free</td>										
									</tr>
									<tr>
										<td>Cart Grand Total</td>
										<td id="grand_total"><span></span></td>
									</tr>
								</table>
							</td>
						</tr> 
					</tbody>
				</table>
			</div> {% endcomment %}
			<div class="payment-options">
					<span>
						<label><input type="checkbox"> Direct Bank Transfer</label>
					</span>
					<span>
						<label><input type="checkbox" disabled="true"> Check Payment</label>
					</span>
					<span>
						<label><input type="checkbox"> Paypal</label>
					</span>
				</div>
		</div>
	</section> <!--/#cart_items-->
	
	</div>
</div>
{% endblock  %}
	
{% block counter %}
<script src="{% static 'js/jquery.js' %}"></script>
<script>
  function grandTotal(){
           $.ajax({
               url:"{% url 'products:get_cart_data' %}",
               type:'get',
               success:function(data){
                   //p = Math.round(100-((data.offer/data.total)*100),2)
                   //save = data.total-data.offer;
				    gtotal = data.total + 2
                   $("#item_total").html("&#x20A6;"+data.total);
                    $("#quantity").html("QUANTITY: "+data.quantity+" Items");
					$("#cartitems").html(data.quantity);
                    $("#grand_total").html("&#8358;"+ gtotal+".00");
                    //$("#btamt").html("&#8377;"+data.offer);

               }
           })
       }
       grandTotal();

       function change_quan(id,action){
           let old = $("#cart"+id).val();
            
           quan = 0
           if(action=="plus"){
               quan += parseInt(old)+1
           }else{
               quan += parseInt(old)-1
           }
           


           $("#cart"+id).val(quan);
           
           $.ajax({
               url:"{% url 'products:change_quan' %}",
               type:"get",
               data:{cid:id, quantity:quan},
               success:function(data){
                   grandTotal();
                 if(data==0){
                    remove_cart(id);
                 }
               }
           })
       }

       function remove_cart(id){
           $.ajax({
               url:"{% url 'products:change_quan' %}",
               data:{delete_cart:id},
               success:function(data){
                    grandTotal();
                    $("#row"+id).hide();
               }

           })
       }
</script>
<div id="fh5co-started">
<div class="container">
<div class="row animate-box">

</div> 
</div>
</div>
</div>

{% endblock counter %}