account/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name='account'

urlpatterns = [
  path('', views.index, name='userprofile'),
  path('validate-username', csrf_exempt(views.UsernamevalidationView.as_view()), name='validate-username'),
  path('validate-email', csrf_exempt(views.EmailValidation.as_view()), name='validate-email'),
  path('activate/<uid64>/<token>/', views.VerificationView.as_view(), name='activate'),
  path('update/', views.profile_update, name='update'),
  path('change_password/', views.update_password, name='change_password'),
  path('whishlist/', views.whishlist,name='whishlist'),
  path('add_to_wishlist/<int:id>/', views.add_to_whishlist, name='add_to_wishlist'),
]

agropoultry/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from home.views import aboutUs, contactUs, SearchResultsView,searchresults
from product.views import process_payment, payment_done, payment_cancelled
from account.views import RegistrationView,LoginView,logoutPage
from django.contrib.auth import views as auth_views
# from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('products/', include('product.urls', namespace='products')),
    path('services/', include('service.urls', namespace='services')),
    path('register/', RegistrationView.as_view(), name='register'),
    path('account/', include('account.urls', namespace='account')),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search/', searchresults, name='search_results'),
    # path('validate-username', csrf_exempt(UsernamevalidationView.as_view()), name='validate-username'),
    # path('validate-email', csrf_exempt(EmailValidation.as_view()), name='validate-email'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logoutPage,name='logout'),
    path('about/', aboutUs, name='about'),
    path('contact/', contactUs, name='contact'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('process_payment/', process_payment, name='process_payment'),
    path('payment_done/', payment_done, name='payment_done'),
    path('payment_cancelled/', payment_cancelled, name='payment_cancelled'),
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace="social")),
    # authentication views from django
    path('reset_password/', 
    auth_views.PasswordResetView.as_view(template_name='account/password_reset.html'), 
    name='password_reset'),
    path('reset_password/done/', 
    auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_sent.html'), 
    name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form.html'), 
    name='password_reset_confirm'),
    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), 
    name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .import views


app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    
]

product/urls.py
from django.urls import path
from .import views

app_name='products'

urlpatterns = [
    path('', views.index, name='products'),
    path('cart/', views.add_to_cart, name='cart_details'),
    path('get_cart_data/', views.get_cart_data, name='get_cart_data'),
    path("change_quan",views.change_quan,name="change_quan"),
    path('checkout/', views.checkout, name='checkout'),
    path('<int:id>/<str:slug>/',views.product_details, name='product_details'),
    path('category/<str:category_slug>/', views.show_category, name='show_category'),
    path('<str:cslug>/', views.category_products, name='category_products'), 

    ] 

service/urls.py
from django.urls import path
from .import views
app_name = 'services'


urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/', views.service_detail, name='service_detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title> 
	{% block title %}
	Inuwa agro poult hatchery Ltd

    {% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{% block description %}automated equipment, automated instrument, Poultry farm equipment,poultry chicken transport cages,plastic chicken turnover box,chicken cages,poultry cage{% endblock %}" />
	<meta name="keywords" content="{% block keywords %}poultry, hatchery ,agricultural machines,Poultry equipment，Poultry farming equipment, Consulting Services, Training{% endblock %}" />
	

	

  	<!-- Facebook and Twitter integration --> 
	{% comment %} <meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" /> {% endcomment %}

	<!-- <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet"> -->
	<!-- <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i" rel="stylesheet"> -->
	 <!-- Favicon  -->
    <link rel="icon" href="{% static 'images/inuwalogo.png' %}">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/app.js' %}"></script>
	<script src="{% static 'js/cart.js' %}"></script>
<script>
    function grandTotal(){
         $.ajax({
               url:"{% url 'products:get_cart_data' %}",
               type:'get',
               success:function(data){
                   p = Math.round(100-((data.offer/data.total)*100),2)
                   //save = data.total-data.offer;
				   gtotal = data.total + 2
                   $("#item_total").html("&#x20A6;"+data.total);
                    $("#quantity").html(data.quantity+" Items");
					$("#cartitems").html(data.quantity);
                    $("#grand_total").html("&#8358;"+gtotal+ ".00");
                    
               }
           })
       }
    grandTotal(); 

      function change_quan(id,action){
           let old = $("#cart"+id).val();
            
           quan = 0
           if(action=="plus"){
               quan += parseInt(old)+1
           }else{
               quan += parseInt(old)-1
           }
           


          $("#cart"+id).val(quan);
           
           $.ajax({
               url:"{% url 'products:change_quan' %}",
               type:"get",
               data:{cid:id, quantity:quan},
               success:function(data){
                   grandTotal();
                 if(data==0){
                    remove_cart(id);
                 }
               }
           })
       } 

       function remove_cart(id){
           $.ajax({
               url:"{% url 'products:change_quan' %}",
               data:{delete_cart:id},
               success:function(data){
                    grandTotal();
                    $("#row"+id).hide();
               }

           })
      }
	      
</script>
	
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
     {% block header %}
    
	 {% endblock header %}
	</head>
	<body>
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-2">
					<div id="fh5co-logo"><a href="/"><img class="mix-blend-mode" src="{% static 'images/inuwalogo.png' %}" width="180" height="150"/></a></div>
				</div>
				<div class="col-md-6 col-xs-6 text-center menu-1">
					<ul>
						<li class="has-dropdown">
							<a href="{% url 'products:products' %}">Products</a>
							<ul class="dropdown">
							  {% for cat in pcategories %}
							  
								<li class="has-dropdown">
								 <a href="{% url 'products:show_category' cat.slug %}">{{ cat.title }}</a>
								   {% comment %} <ul class="dropdown">
								    <li><a href="#">Turkeys</a></li>
									<li><a href="#">Geese</a></li>
									<li><a href="#">Ducks</a></li>
									<li><a href="#">Quails</a></li>
								   </ul> {% endcomment %}
								</li>
								{% endfor %}
								{% comment %} <li><a href="#">Equipments</a></li>  {% endcomment %}
								 {% comment %} {% endfor %} {% endcomment %}
							</ul>
						</li>
						<li><a href="{% url 'about' %}">About</a></li>
						<li class="has-dropdown">
							<a href="{% url 'services:index' %}">Services</a>
							{% comment %} <ul class="dropdown">
								<li><a href="#">Consultation</a></li>
								<li><a href="#">Training</a></li>
								<li><a href="#">Repairs & Installations</a></li>
								
							</ul> {% endcomment %}
						</li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
						{% if user.id is not None %}
						 <li><a href="#"><i class="icon-bell"></i></a></li>
						{% else %}
						{% endif %}
						
						<li class="has-dropdown">
						<a href="#"><i class="icon-lock login"></i> Account</a>
						<ul class="dropdown">
						    {% comment %} {% for auth in backends.associated %}
							{% if auth.provider == 'facebook' %}
							<li>
						     <span><img src="{{ auth.extra_data.picture.data.url }}" style="height:40px; border-radius:30%;"></span>
						     <a href="{% url 'logout' %}">logout</a>
						    </li>
							{% else %}
							{% endif %}
							
							{% endfor %} {% endcomment %}
							
						     {% if user.id is not None  %}

						     <li>
						     <span>
							 <img src="{% if userprofile.image %}{{ userprofile.image.url }}{% else %}{% static 'images/userimage.png' %}{% endif %}" style="height:40px; border-radius:30%;">
							 </span>
						     <a href="{% url 'logout' %}">logout</a>
						    </li>
							<li><a href="{% url 'account:userprofile' %}">Profile</a></li>
						    {% else %} 
						    <li>
						    <a href="{% url 'login' %}">Login</a></li>
							<li><a href="{% url 'register' %}">Sign up</a></li>
						     {% endif %} 
							
						</ul>
						</li>
					</ul>
				</div>
				<div class="col-md-3 col-xs-4 text-right hidden-xs menu-2">
					<ul>
						<li class="search">
						<form method="get" action="{% url 'search_results' %}">
							<div class="input-group">
						      <input type="text" placeholder="Search.." name="q">
						      <span class="input-group-btn">
						        <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
						      </span>
						    </div>
						</form>
						</li>
						{% if request.user.is_authenticated %}
						<li class="shopping-cart"><a href="{% url 'products:cart_details' %}" class="cart"><span><small  id="cartitems" >0</small><i class="icon-shopping-cart"></i></span></a></li>
						{% else %}
						{% endif %}
                       
					</ul>
					
				</div>
			</div>
			
		</div>
	</nav>
	
	{% block aside %}
	
	{% endblock aside %}

   {% block services %}
   
   {% endblock services %}
	{% block products %}
	
	{% endblock products %}
	
	{% block testimonial %}
	
	{% endblock testimonial %}
	

{% block counter %}

{% endblock counter %}
{% block newsletter %}

{% endblock newsletter %}

  {% comment %} <div class="cartBox">
		<div class="cart">
			<i class="fa fa-close"></i>
			<h1>Cart</h1>
		</div>
  </div> {% endcomment %}

	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-4 fh5co-widget">
					<h3><a href="/"><img class="mix-blend-mode" src="{% static 'images/inuwalogo.png' %}" width="180" height="150"/></a></h3>
					<p>We truly serve the best.</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'about' %}">About</a></li>
						{% comment %} <li><a href="#">Help</a></li> {% endcomment %}
						<li><a href="{% url 'contact' %}">Contact</a></li>
						{% comment %} <li><a href="#">Terms</a></li>
						<li><a href="#">Meetups</a></li> {% endcomment %}
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'products:products' %}">Products</a></li>
						<li><a href="#">Categories</a></li>
						{% comment %} <li><a href="#">Testimonials</a></li>
						<li><a href="#">Handbook</a></li>
						<li><a href="#">Held Desk</a></li> {% endcomment %}
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<ul class="fh5co-footer-links">
						<li><a href="#">Find Designers</a></li>
						<li><a href="#">Find Developers</a></li>
						{% comment %} <li><a href="#">Teams</a></li> {% endcomment %}
						<li><a href="#">Advertise</a></li>
						{% comment %} <li><a href="#">API</a></li> {% endcomment %}
					</ul>
				</div>
			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; Inuwa Agro  All Rights Reserved.</small> 
					</p>
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/cart.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>
    
	</body>
</html>

templates/base_auth.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}

{% endblock title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Inuwa Agro description{% block description %}{% endblock %}" />
<meta name="keywords" content="Inuwa Agro keywords{% block keywords %}{% endblock %}" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
{% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> {% endcomment %}
 <link rel="icon" href="{% static 'images/inuwalogo.png' %}">

<link href="{% static 'account/css/style.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/icomoon.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% comment %} <link href="{% static 'account/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/> {% endcomment %}

<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
 {% block header %}

{% endblock header %}
</head>
<body>
	{% block content %}
    
    {% endblock content %}
</body>
</html>